#ifndef BYTECODECONSTANTS_H
#define BYTECODECONSTANTS_H

#define IDENTIFIER_LENGTH 25

enum ConstPoolTag
{
	METHOD_REF = 1,
	CLASS_REF = 2,
	STRING_CONST = 3,
	INT_CONST = 4,
	REAL_CONST = 5
};

#endif // BYTECODECONSTANTS_H
